// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.grpc.lucas.domain;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 result = 2;</code>
   * @return The result.
   */
  int getResult();
}
