// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.grpc.lucas.domain;

public final class CalculatorProto {
  private CalculatorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NumbersToOperate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NumbersToOperate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\"=\n\020NumbersToOperate\022\023" +
      "\n\013firstNumber\030\001 \001(\005\022\024\n\014secondNumber\030\002 \001(" +
      "\005\".\n\013APIResponse\022\017\n\007message\030\001 \001(\t\022\016\n\006res" +
      "ult\030\002 \001(\0052\303\001\n\ncalculator\022&\n\003sum\022\021.Number" +
      "sToOperate\032\014.APIResponse\022-\n\ndifference\022\021" +
      ".NumbersToOperate\032\014.APIResponse\0221\n\016multi" +
      "plication\022\021.NumbersToOperate\032\014.APIRespon" +
      "se\022+\n\010division\022\021.NumbersToOperate\032\014.APIR" +
      "esponseB+\n\026com.grpc.hoogle.domainB\017Calcu" +
      "latorProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NumbersToOperate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NumbersToOperate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NumbersToOperate_descriptor,
        new java.lang.String[] { "FirstNumber", "SecondNumber", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "Message", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
