// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.grpc.lucas.domain;

public interface NumbersToOperateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NumbersToOperate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstNumber = 1;</code>
   * @return The firstNumber.
   */
  int getFirstNumber();

  /**
   * <code>int32 secondNumber = 2;</code>
   * @return The secondNumber.
   */
  int getSecondNumber();
}
